# Makefile
run-dist: #run executable file
		./build/install/app/bin/app

build: #build project
		./gradlew installDist

clean: #clean last build
		./gradlew clean

chk: #apply checkstyleMain
		./gradlew checkstyleMain
